version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - volume:/data
    networks:
      - network

volumes:
  volume:
    name: infrastructure_postgresql

networks:
  network:
    driver: bridge
    name: infrastructure_postgresql
