version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    volumes:
      - volume:/var/lib/rabbitmq
    networks:
      - network

volumes:
  volume:
    name: infrastructure_rabbitmq

networks:
  network:
    driver: bridge
    name: infrastructure_rabbitmq
