version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:6.0-jammy
    ports:
      - '27017:27017'
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - volume:/data/db
    networks:
      - network

volumes:
  volume:
    name: infrastructure_mongodb

networks:
  network:
    driver: bridge
    name: infrastructure_mongodb
