version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - volume:/var/lib/mysql
    networks:
      - network

volumes:
  volume:
    name: infrastructure_mysql

networks:
  network:
    driver: bridge
    name: infrastructure_mysql
